/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eSteamRegister_t)(s3eSteamCallback callbackID, s3eCallback callbackFn, void* userData);
typedef  s3eResult(*s3eSteamUnRegister_t)(s3eSteamCallback callbackID, s3eCallback callbackFn);
typedef    s3eBool(*s3eSteamStart_t)();
typedef    s3eBool(*s3eSteamStarted_t)();
typedef    s3eBool(*s3eSteamRestartAppIfNecessary_t)(uint32 unOwnAppID);
typedef const char *(*s3eSteamGetCurrentGameLanguage_t)();
typedef    s3eBool(*s3eSteamStoreStats_t)();
typedef    s3eBool(*s3eSteamRequestCurrentStats_t)();
typedef       void(*s3eSteamUpdate_t)();
typedef    s3eBool(*s3eSteamGetAchievement_t)(const char* pchName);
typedef    s3eBool(*s3eSteamSetAchievement_t)(const char* pchName);
typedef    s3eBool(*s3eSteamClearAchievement_t)(const char* pchName);
typedef        int(*s3eSteamGetStatInt_t)(const char* pchName);
typedef      float(*s3eSteamGetStatFloat_t)(const char* pchName);
typedef    s3eBool(*s3eSteamSetStatInt_t)(const char* pchName, int nData);
typedef    s3eBool(*s3eSteamSetStatFloat_t)(const char* pchName, float fData);
typedef    s3eBool(*s3eSteamLeaderboardInit_t)(const char* pchName);
typedef    s3eBool(*s3eSteamLeaderboardUploadScore_t)(const char* pchName, int32 value, s3eBool forceUpdate);
typedef        int(*s3eSteamLeaderboardGetEntryCount_t)(const char* pchName);
typedef    s3eBool(*s3eSteamLeaderboardDownloadEntries_t)(const char* pchName, s3eSteamELeaderboardDataRequest eLeaderboardData, int nRangeStart, int nRangeEnd);
typedef    s3eBool(*s3eSteamIsPurchased_t)(uint32 appId);
typedef    s3eBool(*s3eSteamIsSteamOverlayActive_t)();
typedef       void(*s3eSteamPurchase_t)(uint32 appId);

/**
 * struct that gets filled in by s3eSteamRegister
 */
typedef struct s3eSteamFuncs
{
    s3eSteamRegister_t m_s3eSteamRegister;
    s3eSteamUnRegister_t m_s3eSteamUnRegister;
    s3eSteamStart_t m_s3eSteamStart;
    s3eSteamStarted_t m_s3eSteamStarted;
    s3eSteamRestartAppIfNecessary_t m_s3eSteamRestartAppIfNecessary;
    s3eSteamGetCurrentGameLanguage_t m_s3eSteamGetCurrentGameLanguage;
    s3eSteamStoreStats_t m_s3eSteamStoreStats;
    s3eSteamRequestCurrentStats_t m_s3eSteamRequestCurrentStats;
    s3eSteamUpdate_t m_s3eSteamUpdate;
    s3eSteamGetAchievement_t m_s3eSteamGetAchievement;
    s3eSteamSetAchievement_t m_s3eSteamSetAchievement;
    s3eSteamClearAchievement_t m_s3eSteamClearAchievement;
    s3eSteamGetStatInt_t m_s3eSteamGetStatInt;
    s3eSteamGetStatFloat_t m_s3eSteamGetStatFloat;
    s3eSteamSetStatInt_t m_s3eSteamSetStatInt;
    s3eSteamSetStatFloat_t m_s3eSteamSetStatFloat;
    s3eSteamLeaderboardInit_t m_s3eSteamLeaderboardInit;
    s3eSteamLeaderboardUploadScore_t m_s3eSteamLeaderboardUploadScore;
    s3eSteamLeaderboardGetEntryCount_t m_s3eSteamLeaderboardGetEntryCount;
    s3eSteamLeaderboardDownloadEntries_t m_s3eSteamLeaderboardDownloadEntries;
    s3eSteamIsPurchased_t m_s3eSteamIsPurchased;
    s3eSteamIsSteamOverlayActive_t m_s3eSteamIsSteamOverlayActive;
    s3eSteamPurchase_t m_s3eSteamPurchase;
} s3eSteamFuncs;
